version: '3.9'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 4306:4306
    environment:
      MYSQL_DATABASE: db_prod
      MYSQL_ROOT_PASSWORD: pipassword
      MYSQL_TCP_PORT: 4306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    environment:
      ADMINER_DEFAULT_SERVER : db:4306
      ADMINER_DESIGN: hydra
  api:  
    image: amazoncorretto:17-alpine
    restart: always
    volumes:
      - type: bind
        source: ../../../backend/target
        target: /opt/target
    entrypoint: ["java", "-jar", "/opt/target/Backend-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
    ports:
      - 8080:8080
